name: Build iOS IPA (Unsigned)
on:
  workflow_dispatch:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: macos-latest  # 使用GitHub当前支持的最新macOS环境
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'  # 稳定版，兼容性最好
          channel: 'stable'
          
      - name: Initialize iOS project
        run: flutter create . --platforms=ios --no-overwrite
          
      - name: Install dependencies
        run: flutter pub get
         - name: Disable Xcode code signing
        run: |
          # 强制禁用签名
          echo "CODE_SIGNING_ALLOWED = NO;" >> ios/Runner.xcodeproj/project.pbxproj
          echo "CODE_SIGNING_REQUIRED = NO;" >> ios/Runner.xcodeproj/project.pbxproj
      
      - name: Build IPA (unsigned)
        run: |
          flutter build ios --release --no-codesign --no-tree-shake-icons
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload/
          zip -r unsigned_ipa.ipa Payload/
          
      
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: build/ios/iphoneos/unsigned_ipa.ipa
